export const USERNAME_PREFIX = '--username=';
export const EXIT_KEY = '.exit';
export const UP_KEY = 'up';
export const CD_KEY = 'cd';
export const LS_KEY = 'ls';
export const CAT_KEY = 'cat';
export const ADD_KEY = 'add';
export const RN_KEY = 'rn';
export const CP_KEY = 'cp';
export const MV_KEY = 'mv';
export const RM_KEY = 'rm';
export const OS_KEY = 'os';
export const HASH_KEY = 'hash';
export const COMPRESS_KEY = 'compress';
export const DECOMPRESS_KEY = 'decompress';
export const ERROR = 'Operation failed';
